#!/usr/bin/env python3
"""Build a ground model with a chosen friction coefficient, and point worlds at it.

    python3 script/make_slippery_floor.py --mu 0.4 --world <a.world> [--world <b.world>]
    python3 script/make_slippery_floor.py --mu 0.7 --world <a.world> --dry-run

WHY THIS EXISTS
    The shipped simulation has effectively unlimited traction. ODE takes the
    SMALLER mu of the two contacting surfaces; the wheels declare mu=1, mu2=1 and
    every ground model declares mu=100, mu2=50, so the contact runs at mu=1.0 --
    the top of the published dry-clean-concrete range. slip1/slip2 are pinned at
    0 on every ground model, which disables force-dependent slip entirely, so
    contact is rigid until Coulomb traction is exceeded.

    Measured consequence: integrating rear-wheel angle against true path length
    over the five allsensor bags gives encoder/truth ratios of 0.998 to 1.008.
    Under 1% slip, and on one bag the encoder under-reads, which cannot be slip
    at all. The wheel-odometry drift of 2.15-6.57% reported in Chapter 4 is
    therefore dominated by the yaw-rate geometry, not by lost traction.

    That matters because it is the EKF baseline's best case. Dead reckoning is
    being scored on a floor where the wheels cannot slip, which is the one
    condition where it cannot fail. This script makes traction an experimental
    factor so that the visual and proprioceptive estimators can be compared where
    the encoder is actually wrong.

WHY A SEPARATE MODEL, NOT A WORLD EDIT
    Same reason as make_plain_floor.py: friction lives inside the shared ground
    model, so editing it in place changes every world at once. We generate a
    sibling model and swap the include's uri. The meshes are NOT copied -- they
    are unchanged, so the new model references the source model's meshes through
    model://, which Gazebo resolves globally.

CHOOSING mu
    Published rubber-on-concrete coefficients, for orientation rather than as a
    citation:

        dry clean concrete          0.7 - 1.0
        sealed or polished concrete 0.5 - 0.7     <- typical warehouse
        wet concrete                0.4 - 0.6
        wet polished, light spill   0.2 - 0.4

    The shipped 1.0 sits at the optimistic end of the first band. 0.7 is a good
    dry warehouse floor, 0.4 a wet or polished one, 0.2 a contaminated patch.

    mu2 (lateral) is set to mu/2, preserving the 2:1 longitudinal-to-lateral
    ratio the stock ground models already use. Real tyres grip less sideways
    than forwards, so a 1:1 ratio would be the less realistic choice.

WHAT THIS SCRIPT DOES NOT DO
    slip1/slip2 stay at 0 unless --slip is given. Force-dependent slip is the
    physically better model -- slip velocity proportional to tangential force,
    rather than a hard Coulomb threshold -- but this script has no defensible
    source for a value in m/s/N for these tyres, and inventing one would put an
    unsourced number into the physics. --slip exists so the setting can be
    explored; it is untested and should be reported as such if used.

    Verify the result empirically rather than trusting the number: the
    encoder/truth ratio printed by the slip check is the measured outcome, and it
    is what belongs in the report.
"""

import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(ROOT, 'aws-robomaker-small-warehouse-world')
MODELS = os.path.join(PKG, 'models')

CONFIG = """<?xml version="1.0"?>
<model>
  <name>%s</name>
  <version>1.0</version>
  <sdf version="1.6">model.sdf</sdf>
  <description>
    %s with the contact friction coefficient changed to mu=%s, mu2=%s.
    Geometry and meshes are the source model's, referenced through model://.
    Generated by script/make_slippery_floor.py; do not edit by hand.
  </description>
</model>
"""


def suffix(mu):
    """0.4 -> 'mu04'. A filename component, so no dot."""
    return 'mu' + ('%g' % mu).replace('.', '').replace('-', '')


def ground_in(world_text):
    """Which ground model a world currently includes, with any friction suffix
    stripped.

    Without the strip, re-running at a second mu would treat the FIRST variant as
    the source and chain the names -- ..._plain_mu04_mu02 -- which then inherits
    mu04's friction block as its starting point and silently references mu04's
    meshes. Calibration sweeps re-run this script repeatedly, so that path is the
    normal one, not an edge case.
    """
    found = re.findall(r'model://(aws_robomaker_warehouse_Ground\w*)', world_text)
    if not found:
        return None
    return re.sub(r'_mu\d+$', '', found[0])


def retune(sdf, src, dst, mu, mu2, slip):
    """Rewrite the model name, mesh uris and friction block."""
    sdf = sdf.replace('<model name="%s">' % src, '<model name="%s">' % dst)
    # Meshes are unchanged, so keep pointing at the SOURCE model rather than
    # duplicating several MB of DAE per friction level.
    sdf = re.sub(r'model://%s/meshes/' % re.escape(src),
                 'model://%s/meshes/' % src, sdf)
    for tag, val in (('mu', mu), ('mu2', mu2), ('slip1', slip), ('slip2', slip)):
        sdf, n = re.subn(r'<%s>[^<]*</%s>' % (tag, tag),
                         '<%s>%g</%s>' % (tag, val, tag), sdf)
        if n == 0:
            raise SystemExit('no <%s> in %s/model.sdf -- unexpected ground model'
                             % (tag, src))
    return sdf


def main():
    argv = sys.argv
    if '--mu' not in argv:
        raise SystemExit(__doc__)
    mu = float(argv[argv.index('--mu') + 1])
    slip = float(argv[argv.index('--slip') + 1]) if '--slip' in argv else 0.0
    worlds = [argv[i + 1] for i, a in enumerate(argv) if a == '--world']
    dry = '--dry-run' in argv
    if not worlds:
        raise SystemExit('need at least one --world')
    if not 0 < mu <= 1.0:
        raise SystemExit('--mu must be in (0, 1.0]; above 1.0 the wheels\' own '
                         'mu=1 dominates and nothing changes')
    mu2 = mu / 2.0

    if slip:
        print('WARNING: --slip %g is untested and has no sourced value. Report '
              'it as an unvalidated setting.' % slip)

    made = set()
    for w in worlds:
        if not os.path.isfile(w):
            raise SystemExit('no such world: %s' % w)
        text = open(w).read()
        src = ground_in(text)
        if src is None:
            raise SystemExit('%s includes no ground model' % w)
        dst = '%s_%s' % (src, suffix(mu))

        if dst not in made:
            src_dir, dst_dir = os.path.join(MODELS, src), os.path.join(MODELS, dst)
            sdf = retune(open(os.path.join(src_dir, 'model.sdf')).read(),
                         src, dst, mu, mu2, slip)
            print('%s -> %s   mu %g  mu2 %g  slip %g' % (src, dst, mu, mu2, slip))
            if not dry:
                if os.path.isdir(dst_dir):
                    shutil.rmtree(dst_dir)
                os.makedirs(dst_dir)
                open(os.path.join(dst_dir, 'model.sdf'), 'w').write(sdf)
                open(os.path.join(dst_dir, 'model.config'), 'w').write(
                    CONFIG % (dst, src, '%g' % mu, '%g' % mu2))
                print('  wrote models/%s/ (meshes referenced, not copied)' % dst)
            made.add(dst)

        # Swap both the uri and the instance name, so a world that once included
        # two ground variants cannot end up with duplicate model names.
        out = text.replace('model://%s<' % src, 'model://%s<' % dst)
        out = re.sub(r'(<name>)%s(_\d+)?(</name>)' % re.escape(src),
                     r'\g<1>%s\g<2>\g<3>' % dst, out)
        if out == text:
            print('  %s: already points at %s, unchanged' % (os.path.basename(w), dst))
            continue
        print('  %s: include repointed' % os.path.basename(w))
        if not dry:
            open(w, 'w').write(out)

    if dry:
        print('\n--dry-run: nothing written')
    else:
        print('\nNow verify empirically. Record a bag in the changed world, then '
              'compare encoder-integrated distance against ground truth; the '
              'ratio is the measured slip and is what belongs in the report.')


if __name__ == '__main__':
    main()
