#!/usr/bin/env python3
"""Build a featureless copy of the ground model, and point worlds at it.

    python3 script/make_plain_floor.py --world <a.world> [--world <b.world>] [--dry-run]

WHY A SEPARATE MODEL, NOT A WORLD EDIT
    Nothing about the floor's appearance lives in the .world file. Every world
    just does <include><uri>model://aws_robomaker_warehouse_GroundB_01</uri>, and
    the bays, walkway lines and concrete are all geometry and materials INSIDE
    that shared model's visual mesh. Editing it strips the floor out of every
    world at once. So we generate a sibling model and swap the include's uri.

WHAT GETS REMOVED
    The visual DAE holds two <triangles> batches over one shared vertex array:

      count=12   material #946568 -> GroundB_01.png   the concrete slab (a box)
      count=154  material #946569 -> GroundB_02.png   every painted line

    The markings batch is dropped whole, which deletes every bay outline and
    walkway line. The concrete's <diffuse> is then rewritten from a <texture> to
    a flat <color>, and <library_images> is emptied so no texture is fetched at
    all.

    The flat colour is the MEAN of the concrete texture (0.8138 0.8113 0.8042),
    not an invented grey. The texture's per-channel std is only ~0.037, so mean
    substitution holds albedo and scene brightness essentially fixed and removes
    just the spatial variation -- which is the point if this is a VIO ablation:
    change the texture, not the exposure.

    Vertices are left in place. The marking vertices become unreferenced, which
    is legal COLLADA and costs nothing; renumbering the shared array would risk
    the concrete batch's indices for no gain.

    The COLLISION mesh is copied byte-for-byte. Physics, friction and every baked
    map stay identical to the textured world -- the markings were never in the
    collision mesh (12 triangles) to begin with.

RE-RUN AFTER RESHAPING
    scale_warehouse.py / reshape_floor.py regenerate the canonical visual mesh.
    This model is derived from it, so re-run this script afterwards or the plain
    floor will keep the old slab size.
"""
import re, os, sys, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PKG = os.path.join(ROOT, 'aws-robomaker-small-warehouse-world')
MODELS = os.path.join(PKG, 'models')
SRC = 'aws_robomaker_warehouse_GroundB_01'
DST = 'aws_robomaker_warehouse_GroundB_01_plain'
MARKING_MATERIAL = 'Material #946569'      # the painted-line batch
CONCRETE_MATERIAL = 'Material #946568'
FALLBACK_RGB = (0.813810, 0.811311, 0.804215)   # measured mean of GroundB_01.png

CONFIG = """<?xml version="1.0" ?>
<model>
    <name>%s</name>
    <version>1.0</version>
    <sdf version="1.7">model.sdf</sdf>
    <author>
        <name></name>
        <email></email>
    </author>
    <description>
      %s with a featureless floor: the 154 painted-marking triangles are
      removed and the concrete texture is replaced by its own mean colour.
      Collision geometry is unchanged, so maps and physics match the textured
      model exactly. Generated by script/make_plain_floor.py -- do not hand-edit.
    </description>
</model>
"""


def mean_rgb(png):
    """Mean colour of the concrete texture, so brightness is preserved."""
    try:
        from PIL import Image
        import numpy as np
        a = np.asarray(Image.open(png).convert('RGB')).astype(float) / 255.0
        return tuple(float(a[:, :, i].mean()) for i in range(3))
    except Exception as e:
        print('  (PIL unavailable: %s -- using measured constant)' % e)
        return FALLBACK_RGB


def strip(dae, rgb):
    """Drop the marking triangles, flatten the concrete material, drop images."""
    n = len(dae)

    # 1. the whole markings batch
    pat = r'[ \t]*<triangles[^>]*material="%s".*?</triangles>\n?' % re.escape(MARKING_MATERIAL)
    dae, k = re.subn(pat, '', dae, flags=re.S)
    if k != 1:
        raise SystemExit('expected exactly 1 markings batch, removed %d' % k)

    # 2. its bind_material entry, now dangling
    dae = re.sub(r'<instance_material symbol="%s"[^/]*/>' % re.escape(MARKING_MATERIAL),
                 '', dae)

    # 3. concrete diffuse: <texture .../> -> flat <color>
    m = re.search(r'(<effect id="%s-fx".*?<diffuse>)(.*?)(</diffuse>)'
                  % re.escape(CONCRETE_MATERIAL), dae, re.S)
    if not m or '<texture' not in m.group(2):
        raise SystemExit('concrete diffuse texture not found -- mesh changed?')
    flat = '\n              <color sid="diffuse">%.6f %.6f %.6f 1.000000</color>\n            ' % rgb
    dae = dae[:m.start(2)] + flat + dae[m.end(2):]

    # 4. the markings' effect + material, now bound by nothing. They must go, not
    #    just be ignored: each still names an <init_from> image, and emptying
    #    library_images under a live <texture> leaves a dangling reference.
    for pat in (r'[ \t]*<effect id="%s-fx".*?</effect>\n?' % re.escape(MARKING_MATERIAL),
                r'[ \t]*<material id="%s".*?</material>\n?' % re.escape(MARKING_MATERIAL)):
        dae, k = re.subn(pat, '', dae, flags=re.S)
        if k != 1:
            raise SystemExit('expected 1 match for %s, removed %d' % (pat[:40], k))

    # 5. no textures referenced at all
    dae = re.sub(r'<library_images>.*?</library_images>',
                 '<library_images/>', dae, flags=re.S)
    if '<texture' in dae:
        raise SystemExit('a texture reference survived -- not featureless')
    return dae, n


def main():
    worlds = [sys.argv[i + 1] for i, a in enumerate(sys.argv) if a == '--world']
    dry = '--dry-run' in sys.argv

    src_dir, dst_dir = os.path.join(MODELS, SRC), os.path.join(MODELS, DST)
    vis = os.path.join(src_dir, 'meshes', SRC + '_visual.DAE')
    col = os.path.join(src_dir, 'meshes', SRC + '_collision.DAE')
    png = os.path.join(src_dir, 'materials', 'textures', SRC + '.png')

    rgb = mean_rgb(png)
    plain, before = strip(open(vis).read(), rgb)
    print('  concrete flat colour  %.6f %.6f %.6f' % rgb)
    print('  visual DAE  %d -> %d bytes (markings batch removed)' % (before, len(plain)))

    if not dry:
        if os.path.isdir(dst_dir):
            shutil.rmtree(dst_dir)
        os.makedirs(os.path.join(dst_dir, 'meshes'))
        open(os.path.join(dst_dir, 'meshes', DST + '_visual.DAE'), 'w').write(plain)
        shutil.copyfile(col, os.path.join(dst_dir, 'meshes', DST + '_collision.DAE'))
        # model.sdf: same link, inertia and friction; only the mesh uris move.
        sdf = open(os.path.join(src_dir, 'model.sdf')).read()
        sdf = sdf.replace('<model name="%s">' % SRC, '<model name="%s">' % DST)
        sdf = sdf.replace('model://%s/meshes/%s_' % (SRC, SRC),
                          'model://%s/meshes/%s_' % (DST, DST))
        open(os.path.join(dst_dir, 'model.sdf'), 'w').write(sdf)
        open(os.path.join(dst_dir, 'model.config'), 'w').write(CONFIG % (DST, SRC))
        print('  wrote models/%s/ (visual, collision, model.sdf, model.config)' % DST)

    for w in worlds:
        path = w if os.path.isabs(w) else os.path.join(ROOT, w)
        t = open(path).read()
        t2, k = re.subn(r'model://%s(?![_A-Za-z0-9])' % re.escape(SRC),
                        'model://' + DST, t)
        # the <name> too, so the entity is distinguishable at runtime
        t2 = re.sub(r'<name>%s_(\d+)</name>' % re.escape(SRC),
                    r'<name>%s_\1</name>' % DST, t2)
        print('  %-52s %d ground uri(s) repointed' % (os.path.basename(path), k))
        if k != 1:
            print('    WARNING: expected 1, got %d' % k)
        if not dry:
            open(path, 'w').write(t2)

    if dry:
        print('\n(dry run -- nothing written)')


if __name__ == '__main__':
    main()
